language: python
python:
  - "2.7"
# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install coveralls
    - pip install yapf
# Run unit tests
script:
    - coverage run --source telescope -m unittest discover
    - yapf --diff --recursive --style google ./ # Run Python linter
after_success:
    coveralls

sudo: false
