language: python
python:
  - "2.7"
# Install dependencies
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
# Run unit tests
script: python -m unittest discover
